### ISSUE TITLE
Problemas al lanzar el scriptq

### ISSUE THREAD

**Issue by ronellcl** [DiegoIdeas/Servel#1]
Estimado, al ejecutar el script aparece el siguiente error:

Traceback (most recent call last):
  File "toolkit.py", line 2, in <module>
    from servel import ServelFiles

a qué se debe el error? se puede reparar? 
muchísimas gracias.

**Comment by DiegoIdeas** [comment]
se debe a que seguramente no estas usando python 3.7 pues la linea del import que se hace mencion usa un compilado exclusivo para python 3.7 con el que se ofusco el codigo real que hace la magia ...tal y cual como se definio en los requerimientos es solo python 3.7, ni 3.8 ni 3.9 ni ningun otro seran factibles.

Como tip creo tampoco funcionaria en teoria con anaconda u otro similar esto requiere python nativo.
